[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.13"

[rpc_endpoints]
anvil = "http://localhost:8545/"
goerli = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
sepolia = "https://ethereum-sepolia-rpc.allthatnode.com"
polygon = "https://polygon-rpc.com"
arbitrum = "https://arbitrum.public-rpc.com"
optimism = "https://1rpc.io/op"
optimism_goerli = "https://goerli.optimism.io"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config